#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# and says "I am invincible!!!" when receiving SIGTERM

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
