#!/usr/bin/env bash
# Infinite loop that prints a message and handles SIGTERM with a custom message

# Define signal handler
trap 'echo "I am invincible!!!"' SIGTERM

# Loop indefinitely
while true
do
  echo "To infinity and beyond"
  sleep 2
done
