#!/usr/bin/env bash
#
i=1
while [ "$i" -le 20 ]; do
if [ "$i" -eq 4 ] || [ "$i" -eq 13 ] || [ "$i" -eq 19 ]; then
echo "bad luck"
elif [ "$i" -eq 7 ] || [ "$i" -eq 16 ]; then
echo "good luck"
else
echo "Best School"
fi
i=$((i + 1))
done
