#!/usr/bin/env bash
#
if [ -e "$FILE" ]; then
  echo "school file exists"
else
  echo "school file does not exist"
fi

if [ -f "$FILE" ]; then
  echo "school is a regular file"
else
  echo "school is not a regular file"
fi

if [ -s "$FILE" ]; then
  echo "school file is not empty"
else
  echo "school file is empty"
fi
