#!/usr/bin/env bash
#
if [ -e "$FILE" ]; then
  echo "school file exists"
fi

if [ -f "$FILE" ]; then
  echo "school is a regular file"
fi

if [ -s "$FILE" ]; then
  echo "school file is not empty"
fi
